spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username:  system
    password:  Zulkar@123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: activity-processor-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fitness.aiservice.model.Activity
        spring.json.trusted.packages: "*"

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent
    key: AIzaSyD_aRY38PXaL846xg2HmiUTVBWIPiTbN44


kafka:
  topic:
    name: activity-events

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

server:
  port: 8083