spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username:  system
    password:  Zulkar@123
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.OracleDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081